services:
  todo-app:
    image: todo-app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:5000
    env_file:
      - .env
    platform: linux/amd64
    volumes:
      - type: bind
        source: todo_app
        target: /todo_app