apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo-app
          image: todo-app:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
          env:
          - name: FLASK_APP
            value: todo_app/app
          - name: LOG_LEVEL
            value: DEBUG
          - name: LOGGLY_TOKEN
            valueFrom:
              secretKeyRef:
                name: logglytoken
                key: LOGGLY_TOKEN
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secretkey
                key: SECRET_KEY
          - name: DATABASE_NAME
            value: dev-database
          - name: ITEMS_COLLECTION_NAME
            value: to_do_items
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: connectionstring
                key: CONNECTION_STRING