services:
  todo-app:
    image: todo-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    ports:
      - 8080:5000
    env_file:
      - ../env/.env
    platform: linux/amd64
