name: Continuous Integration
on:
  push:
      paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'docker/docker-compose-*.yaml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'docker/docker-compose-*.yaml'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --file docker/Dockerfile --target test --tag todo-app-tests .
    - run: docker run todo-app-tests
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/exercise-9'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build --file docker/Dockerfile --target production --tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.sha }} .
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.sha }}
